//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lewd.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="lewdParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IlewdListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] lewdParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] lewdParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.docLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocLevelExpression([NotNull] lewdParser.DocLevelExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.docLevelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocLevelExpression([NotNull] lewdParser.DocLevelExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] lewdParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] lewdParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] lewdParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] lewdParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignmentLHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentLHS([NotNull] lewdParser.AssignmentLHSContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignmentLHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentLHS([NotNull] lewdParser.AssignmentLHSContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignmentRHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentRHS([NotNull] lewdParser.AssignmentRHSContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignmentRHS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentRHS([NotNull] lewdParser.AssignmentRHSContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] lewdParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] lewdParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDef([NotNull] lewdParser.FunctionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDef([NotNull] lewdParser.FunctionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] lewdParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] lewdParser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] lewdParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] lewdParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] lewdParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] lewdParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollection([NotNull] lewdParser.CollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollection([NotNull] lewdParser.CollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] lewdParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] lewdParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol([NotNull] lewdParser.SymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol([NotNull] lewdParser.SymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecord([NotNull] lewdParser.RecordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecord([NotNull] lewdParser.RecordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr([NotNull] lewdParser.StrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr([NotNull] lewdParser.StrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.recordEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordEntry([NotNull] lewdParser.RecordEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.recordEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordEntry([NotNull] lewdParser.RecordEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.truefalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTruefalse([NotNull] lewdParser.TruefalseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.truefalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTruefalse([NotNull] lewdParser.TruefalseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] lewdParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] lewdParser.NameContext context);
}
