//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lewd.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IlewdListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class lewdBaseListener : IlewdListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] lewdParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] lewdParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.docLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocLevelExpression([NotNull] lewdParser.DocLevelExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.docLevelExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocLevelExpression([NotNull] lewdParser.DocLevelExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] lewdParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] lewdParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] lewdParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] lewdParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignmentLHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentLHS([NotNull] lewdParser.AssignmentLHSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignmentLHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentLHS([NotNull] lewdParser.AssignmentLHSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.assignmentRHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentRHS([NotNull] lewdParser.AssignmentRHSContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.assignmentRHS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentRHS([NotNull] lewdParser.AssignmentRHSContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] lewdParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] lewdParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDef([NotNull] lewdParser.FunctionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDef([NotNull] lewdParser.FunctionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionBody([NotNull] lewdParser.FunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionBody([NotNull] lewdParser.FunctionBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] lewdParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] lewdParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] lewdParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] lewdParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection([NotNull] lewdParser.CollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection([NotNull] lewdParser.CollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] lewdParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] lewdParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbol([NotNull] lewdParser.SymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbol([NotNull] lewdParser.SymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.record"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecord([NotNull] lewdParser.RecordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.record"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecord([NotNull] lewdParser.RecordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] lewdParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] lewdParser.StrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.recordEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordEntry([NotNull] lewdParser.RecordEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.recordEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordEntry([NotNull] lewdParser.RecordEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.truefalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTruefalse([NotNull] lewdParser.TruefalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.truefalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTruefalse([NotNull] lewdParser.TruefalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="lewdParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] lewdParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="lewdParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] lewdParser.NameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
