//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lewd.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class lewdLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, StringLiteral=12, SYMBOL_TEXT=13, NUMBER_TEXT=14, PERIOD=15, 
		STRING=16, WS=17, COMMENT=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "StringLiteral", "HexDigit", "EscapeSequence", "OctalEscape", 
		"UnicodeEscape", "SYMBOL_TEXT", "NUMBER_TEXT", "ALPHANUMERIC", "DIGIT", 
		"PERIOD", "TEXT", "STRING", "SPECIAL_SYMBOL_CHAR", "WS", "COMMENT"
	};


	public lewdLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public lewdLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'('", "')'", "'=>'", "'['", "']'", "'{'", "'}'", "'->'", 
		"'true'", "'false'", null, null, null, "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"StringLiteral", "SYMBOL_TEXT", "NUMBER_TEXT", "PERIOD", "STRING", "WS", 
		"COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lewd.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static lewdLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x14', '\xC3', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', 'Z', '\n', '\r', 
		'\f', '\r', '\xE', '\r', ']', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', 'g', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x5', '\x10', 'r', '\n', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '}', '\n', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\x81', '\n', '\x12', 
		'\f', '\x12', '\xE', '\x12', '\x84', '\v', '\x12', '\x3', '\x13', '\x5', 
		'\x13', '\x87', '\n', '\x13', '\x3', '\x13', '\x6', '\x13', '\x8A', '\n', 
		'\x13', '\r', '\x13', '\xE', '\x13', '\x8B', '\x3', '\x13', '\x3', '\x13', 
		'\a', '\x13', '\x90', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x93', 
		'\v', '\x13', '\x5', '\x13', '\x95', '\n', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\a', '\x13', '\x99', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'\x9C', '\v', '\x13', '\x5', '\x13', '\x9E', '\n', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x5', '\x14', '\xA2', '\n', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x6', '\x18', '\xAB', '\n', '\x18', '\r', '\x18', '\xE', '\x18', 
		'\xAC', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x6', '\x1A', '\xB2', 
		'\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xB3', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\xBA', '\n', '\x1B', 
		'\f', '\x1B', '\xE', '\x1B', '\xBD', '\v', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\xBB', '\x2', 
		'\x1C', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\x2', '\x1D', '\x2', '\x1F', '\x2', '!', 
		'\x2', '#', '\xF', '%', '\x10', '\'', '\x2', ')', '\x2', '+', '\x11', 
		'-', '\x2', '/', '\x12', '\x31', '\x2', '\x33', '\x13', '\x35', '\x14', 
		'\x3', '\x2', '\n', '\x4', '\x2', '$', '$', '^', '^', '\x5', '\x2', '\x32', 
		';', '\x43', 'H', '\x63', 'h', '\n', '\x2', '$', '$', ')', ')', '^', '^', 
		'\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x3', '\x2', 
		'\x32', '\x35', '\x3', '\x2', '\x32', '\x39', '\x5', '\x2', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x6', '\x2', ',', '-', '/', '/', '\x31', 
		'\x31', '\x41', '\x41', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x2', '\xCD', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x3', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x39', '\x3', '\x2', '\x2', '\x2', '\a', ';', '\x3', 
		'\x2', '\x2', '\x2', '\t', '=', '\x3', '\x2', '\x2', '\x2', '\v', '@', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x44', '\x3', '\x2', '\x2', '\x2', '\x11', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'H', '\x3', '\x2', '\x2', '\x2', '\x15', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'P', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'V', '\x3', '\x2', '\x2', '\x2', '\x1B', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '\x66', '\x3', '\x2', '\x2', '\x2', '\x1F', 'q', '\x3', '\x2', 
		'\x2', '\x2', '!', 's', '\x3', '\x2', '\x2', '\x2', '#', '|', '\x3', '\x2', 
		'\x2', '\x2', '%', '\x86', '\x3', '\x2', '\x2', '\x2', '\'', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', ')', '\xA3', '\x3', '\x2', '\x2', '\x2', '+', '\xA5', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xA7', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\x31', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x35', '\xB5', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x38', '\a', '?', '\x2', '\x2', '\x38', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '*', '\x2', '\x2', 
		':', '\x6', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '+', '\x2', '\x2', 
		'<', '\b', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '?', '\x2', '\x2', 
		'>', '?', '\a', '@', '\x2', '\x2', '?', '\n', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\a', ']', '\x2', '\x2', '\x41', '\f', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x43', '\a', '_', '\x2', '\x2', '\x43', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\a', '}', '\x2', '\x2', '\x45', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', '\x7F', '\x2', 
		'\x2', 'G', '\x12', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '/', '\x2', 
		'\x2', 'I', 'J', '\a', '@', '\x2', '\x2', 'J', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\a', 'v', '\x2', '\x2', 'L', 'M', '\a', 't', '\x2', 
		'\x2', 'M', 'N', '\a', 'w', '\x2', '\x2', 'N', 'O', '\a', 'g', '\x2', 
		'\x2', 'O', '\x16', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', 'h', '\x2', 
		'\x2', 'Q', 'R', '\a', '\x63', '\x2', '\x2', 'R', 'S', '\a', 'n', '\x2', 
		'\x2', 'S', 'T', '\a', 'u', '\x2', '\x2', 'T', 'U', '\a', 'g', '\x2', 
		'\x2', 'U', '\x18', '\x3', '\x2', '\x2', '\x2', 'V', '[', '\a', '$', '\x2', 
		'\x2', 'W', 'Z', '\x5', '\x1D', '\xF', '\x2', 'X', 'Z', '\n', '\x2', '\x2', 
		'\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\x3', '\x2', 
		'\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', '$', 
		'\x2', '\x2', '_', '\x1A', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\t', 
		'\x3', '\x2', '\x2', '\x61', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\a', '^', '\x2', '\x2', '\x63', 'g', '\t', '\x4', '\x2', '\x2', 
		'\x64', 'g', '\x5', '!', '\x11', '\x2', '\x65', 'g', '\x5', '\x1F', '\x10', 
		'\x2', '\x66', '\x62', '\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '^', '\x2', '\x2', 
		'i', 'j', '\t', '\x5', '\x2', '\x2', 'j', 'k', '\t', '\x6', '\x2', '\x2', 
		'k', 'r', '\t', '\x6', '\x2', '\x2', 'l', 'm', '\a', '^', '\x2', '\x2', 
		'm', 'n', '\t', '\x6', '\x2', '\x2', 'n', 'r', '\t', '\x6', '\x2', '\x2', 
		'o', 'p', '\a', '^', '\x2', '\x2', 'p', 'r', '\t', '\x6', '\x2', '\x2', 
		'q', 'h', '\x3', '\x2', '\x2', '\x2', 'q', 'l', '\x3', '\x2', '\x2', '\x2', 
		'q', 'o', '\x3', '\x2', '\x2', '\x2', 'r', ' ', '\x3', '\x2', '\x2', '\x2', 
		's', 't', '\a', '^', '\x2', '\x2', 't', 'u', '\a', 'w', '\x2', '\x2', 
		'u', 'v', '\x5', '\x1B', '\xE', '\x2', 'v', 'w', '\x5', '\x1B', '\xE', 
		'\x2', 'w', 'x', '\x5', '\x1B', '\xE', '\x2', 'x', 'y', '\x5', '\x1B', 
		'\xE', '\x2', 'y', '\"', '\x3', '\x2', '\x2', '\x2', 'z', '}', '\x5', 
		'-', '\x17', '\x2', '{', '}', '\x5', '\x31', '\x19', '\x2', '|', 'z', 
		'\x3', '\x2', '\x2', '\x2', '|', '{', '\x3', '\x2', '\x2', '\x2', '}', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '~', '\x81', '\x5', '\'', '\x14', 
		'\x2', '\x7F', '\x81', '\x5', '\x31', '\x19', '\x2', '\x80', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '$', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x87', '\a', '/', '\x2', '\x2', '\x86', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x8A', '\x5', ')', '\x15', '\x2', '\x89', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x94', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x91', '\x5', '+', '\x16', '\x2', '\x8E', '\x90', '\x5', ')', '\x15', 
		'\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x92', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\x96', '\x9A', '\x5', '+', '\x16', 
		'\x2', '\x97', '\x99', '\x5', ')', '\x15', '\x2', '\x98', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x89', '\x3', '\x2', '\x2', '\x2', '\x9D', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x9E', '&', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA2', '\x5', '-', '\x17', '\x2', '\xA0', '\xA2', '\x5', 
		')', '\x15', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '(', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA4', '\x4', '\x32', ';', '\x2', '\xA4', '*', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x30', '\x2', '\x2', '\xA6', 
		',', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\t', '\a', '\x2', '\x2', 
		'\xA8', '.', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAB', '\x5', '-', '\x17', 
		'\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAF', '\t', '\b', '\x2', '\x2', '\xAF', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB2', '\t', '\t', '\x2', '\x2', '\xB1', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\x34', '\x3', '\x2', '\x2', '\x2', '\xB5', 
		'\xB6', '\a', '\x31', '\x2', '\x2', '\xB6', '\xB7', '\a', ',', '\x2', 
		'\x2', '\xB7', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBA', '\v', 
		'\x2', '\x2', '\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBD', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBF', '\a', ',', '\x2', '\x2', '\xBF', '\xC0', '\a', '\x31', '\x2', 
		'\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\b', 
		'\x1B', '\x2', '\x2', '\xC2', '\x36', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\x2', 'Y', '[', '\x66', 'q', '|', '\x80', '\x82', '\x86', '\x8B', '\x91', 
		'\x94', '\x9A', '\x9D', '\xA1', '\xAC', '\xB3', '\xBB', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
